### ISSUE TITLE
Diagonal fungus growth allows it to spread through walls

### ISSUE THREAD

**Issue by dsibilly** [NetGnome/hammerogue#3]
As of _92429c4_, fungus can grow both orthagonally and diagonally. In a test session, I observed the fungus using its ability to grow diagonally to breach a 1-unit wide diagonal wall:

```
* * * O
* F O *
F O F *
O O * *
```

I don't know if this behavior is intentional, but I figured I'd bring it some attention in case it is not.

**Possible solutions**:
- Stop diagonal grown of fungus
- Alter the map generation to prohibit the formation of 1-unit wide diagonal walls

**Comment by NetGnome** [comment]
not an issue, diagonal movement will be allowed
